// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: query.sql

package db

import (
	"context"
)

const listProductURLS = `-- name: ListProductURLS :many
SELECT url FROM product
ORDER BY url
`

func (q *Queries) ListProductURLS(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listProductURLS)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var url string
		if err := rows.Scan(&url); err != nil {
			return nil, err
		}
		items = append(items, url)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
